/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogueRoute,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue': typeof CatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalogue'
    | '/contact'
    | '/faq'
    | '/catalogue/$slug'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/faq' | '/catalogue/$slug' | '/catalogue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalogue'
    | '/contact'
    | '/faq'
    | '/catalogue/$slug'
    | '/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogueRoute: typeof CatalogueRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof CatalogueRoute
    }
  }
}

interface CatalogueRouteChildren {
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogueRoute: CatalogueRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
